spring:
  application:
    name: rest-example

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/test}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: test
        jdbc:
          lob:
            non_contextual_creation: true

  jackson:
    default-property-inclusion: non_null
